### ISSUE TITLE
[TASK] Implement release automation with multi-platform binaries

### ISSUE THREAD

**Issue by aoshimash** [aoshimash/crawld#15]
## 📋 Task Overview
Set up automated release process with multi-platform binary builds, semantic versioning, and automated release notes generation.

## 🎯 Objectives
- [ ] Implement automated release workflow with GitHub Actions
- [ ] Build multi-platform binaries (Linux, macOS, Windows)
- [ ] Set up semantic versioning with git tags
- [ ] Generate automated release notes

## 📋 Acceptance Criteria
- [ ] Release workflow triggers on git tags
- [ ] Multi-platform binaries are built and attached to releases
- [ ] Semantic versioning is properly implemented
- [ ] Release notes are automatically generated
- [ ] Binaries include version information

### Implementation Details
- **Package/Module**: `.github/workflows/release.yml`
- **Dependencies**: GitHub Actions, Go cross-compilation
- **Configuration**: Release automation and binary distribution

### Release Targets
- **Linux**: amd64, arm64
- **macOS**: amd64 (Intel), arm64 (Apple Silicon)
- **Windows**: amd64
- **Version embedding**: Build-time version injection

### Code Standards
- [ ] Follow semantic versioning (v1.0.0 format)
- [ ] Include build metadata in binaries
- [ ] Use cross-compilation for all platforms
- [ ] Compress binaries for distribution
- [ ] Include checksums for verification

## 🧪 Testing Requirements
- [ ] Test release workflow with test tags
- [ ] Verify binary functionality on all platforms
- [ ] Test version embedding and display
- [ ] Validate release artifacts
- [ ] Test automated release notes

## 📚 Documentation Requirements
- [ ] Release process documentation
- [ ] Binary distribution documentation
- [ ] Version management documentation

## 🔗 Dependencies
- Depends on: #2 (CI foundation)
- Depends on: #14 (containerization for complete automation)
- Blocks: #16 (documentation needs versioned releases)

## 💡 Implementation Notes
Example release workflow structure:

```yaml
name: Release
on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Build binaries
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=${{ github.ref_name }}" -o crawld-linux-amd64 ./cmd/crawld
        GOOS=linux GOARCH=arm64 go build -ldflags="-X main.version=${{ github.ref_name }}" -o crawld-linux-arm64 ./cmd/crawld
        
        # macOS  
        GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.version=${{ github.ref_name }}" -o crawld-darwin-amd64 ./cmd/crawld
        GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.version=${{ github.ref_name }}" -o crawld-darwin-arm64 ./cmd/crawld
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags="-X main.version=${{ github.ref_name }}" -o crawld-windows-amd64.exe ./cmd/crawld
```

Version embedding:
- Use build-time ldflags for version injection
- Include git commit hash and build date
- Display in --version command

Release features:
- Automated release notes from commit messages
- Binary checksums for verification
- Archive compression (tar.gz for Unix, zip for Windows)
- GitHub Releases integration

## ✅ Definition of Done
- [ ] Release workflow implemented and tested
- [ ] Multi-platform binaries building correctly
- [ ] Version embedding working
- [ ] Automated release notes functional
- [ ] Release process documented
- [ ] Ready for production releases
